### ISSUE TITLE
Relative links aren't working

### ISSUE THREAD

**Issue by FizzBuzz791** [telstrapurple/PurplePersonas#1]
A markdown link like `(Senior Consultant)[seniorconsultant.md]` doesn't resolve as expected.

It breaks the build with "no such file or directory - roles/seniorconsultant.md.md"

Dropping the ".md" causes it to be relative to where-ever it's linked from, for example "consultant/seniorconsultant", which also doesn't work.

Adding a "./" to the front has no effect on either of the above.
---
It might be to do with how we're parsing the slugs...

**Comment by RobFaie** [comment]
Once the custom domain is setup I would expect `(Senior Consultant)[/seniorconsultant]` to work based on what is currently deployed.

**Comment by FizzBuzz791** [comment]
Yeah, I don't know what was broken or how we fixed it actually, but they seem to work fine now and the custom domain shouldn't affect that.
